#! /usr/bin/ksh
#

infile=$1
protdir=$infile.result

mkdir $protdir


csfn_fcvreversenorm \
  -k FCV#pica#pica3#title \
  -u \
  -e $protdir/${infile}_norm_errors.txt \
  -b $protdir/${infile}_norm_sequence.txt \
  -s $protdir/${infile}_norm_statistics.txt \
  < ./$infile.pic3 \
  > ./$infile.pp \
  2> $protdir/syserror.txt


csfn_valnorm \
  -k VALTAB#title#offline \
  -o GBV-VAL \
  -u \
  -e ${infile}_val_errors.txt \
  -b $protdir/${infile}_val_sequence.txt \
  -s $protdir/${infile}_val_statistics.txt \
  < ./$infile.pp \
  > $protdir/${infile}_val_.out \
  2> $protdir/${infile}_val_syserror.txt